import Head from "next/head";
import { Inter } from "next/font/google";
import FollowerCard from "@/components/FollowerCard";
import TodayCard from "@/components/TodayCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Social media dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <FollowerCard
        logoPath="/icon-facebook.svg"
        type="facebook"
        account="@nathanf"
        follower="1044"
        upOrDown="down"
        count="12"
        borderTopColor="border-t-facebook"
      />
      <br />
      <TodayCard
        label="Page Views"
        logoPath="/icon-facebook.svg"
        type="facebook"
        number="52"
        upOrDown="down"
        percentage="3"
      />
    </>
  );
}
